const FLAG_MAP: Record<string, string> = {
    // Fase de grupos do Brasil (Copa 2026)
    'Marrocos': '🇲🇦',
    'Haiti': '🇭🇹',
    'Escócia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',

    // América do Sul
    'Argentina': '🇦🇷',
    'Uruguai': '🇺🇾',
    'Colômbia': '🇨🇴',
    'Equador': '🇪🇨',
    'Peru': '🇵🇪',
    'Chile': '🇨🇱',
    'Venezuela': '🇻🇪',
    'Bolívia': '🇧🇴',
    'Paraguai': '🇵🇾',

    // América do Norte e Central
    'EUA': '🇺🇸',
    'Estados Unidos': '🇺🇸',
    'México': '🇲🇽',
    'Canadá': '🇨🇦',
    'Costa Rica': '🇨🇷',
    'Honduras': '🇭🇳',
    'El Salvador': '🇸🇻',
    'Jamaica': '🇯🇲',
    'Panamá': '🇵🇦',
    'Trinidad e Tobago': '🇹🇹',
    'Guatemala': '🇬🇹',
    'Cuba': '🇨🇺',

    // Europa
    'Alemanha': '🇩🇪',
    'França': '🇫🇷',
    'Espanha': '🇪🇸',
    'Portugal': '🇵🇹',
    'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Bélgica': '🇧🇪',
    'Holanda': '🇳🇱',
    'Países Baixos': '🇳🇱',
    'Itália': '🇮🇹',
    'Croácia': '🇭🇷',
    'Sérvia': '🇷🇸',
    'Suíça': '🇨🇭',
    'Dinamarca': '🇩🇰',
    'Áustria': '🇦🇹',
    'Ucrânia': '🇺🇦',
    'Polônia': '🇵🇱',
    'Turquia': '🇹🇷',
    'Romênia': '🇷🇴',
    'Hungria': '🇭🇺',
    'Eslováquia': '🇸🇰',
    'Eslovênia': '🇸🇮',
    'República Tcheca': '🇨🇿',
    'Grécia': '🇬🇷',
    'Albânia': '🇦🇱',
    'Geórgia': '🇬🇪',
    'Noruega': '🇳🇴',
    'Suécia': '🇸🇪',
    'Finlândia': '🇫🇮',
    'País de Gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Irlanda': '🇮🇪',
    'Rússia': '🇷🇺',

    // Ásia
    'Japão': '🇯🇵',
    'Coreia do Sul': '🇰🇷',
    'Austrália': '🇦🇺',
    'Irã': '🇮🇷',
    'Arábia Saudita': '🇸🇦',
    'Qatar': '🇶🇦',
    'China': '🇨🇳',
    'Indonésia': '🇮🇩',
    'Uzbequistão': '🇺🇿',
    'Jordânia': '🇯🇴',
    'Iraque': '🇮🇶',
    'Emirados Árabes': '🇦🇪',

    // África
    'Senegal': '🇸🇳',
    'Nigéria': '🇳🇬',
    'Gana': '🇬🇭',
    'Costa do Marfim': '🇨🇮',
    'Camarões': '🇨🇲',
    'Egito': '🇪🇬',
    'Argélia': '🇩🇿',
    'Tunísia': '🇹🇳',
    'África do Sul': '🇿🇦',
    'Angola': '🇦🇴',
    'Mali': '🇲🇱',
}

export function getCountryFlag(country: string): string {
    return FLAG_MAP[country] ?? ''
}
